cmake_minimum_required(VERSION 3.5)

project(QWidget_Model_View VERSION 1.0.0 LANGUAGES CXX)

add_subdirectory(QTableWidget_basic)
add_subdirectory(QTableWidget_perf)
add_subdirectory(QTableView_standarditemmodel)
add_subdirectory(QTableView_fastmodel)
add_subdirectory(QTableView_fastmodel_first_paint)
